class Stash < Formula
  desc "Interactive launcher that resumes claude / codex / opencode sessions"
  homepage "https://github.com/SectorOPS/Stash"
  version "0.1.0"
  license "MIT"

  # NOTE: this is a placeholder. The real urls/sha256s are generated by
  # scripts/update-formula.sh after `bun build --compile` produces per-platform
  # tarballs in ./dist. See HOMEBREW.md for the release flow.

  on_macos do
    on_arm do
      url "https://github.com/SectorOPS/Stash/releases/download/v0.1.0/stash-0.1.0-darwin-arm64.tar.gz"
      sha256 "REPLACE_ME_DARWIN_ARM64"
    end
    on_intel do
      url "https://github.com/SectorOPS/Stash/releases/download/v0.1.0/stash-0.1.0-darwin-x64.tar.gz"
      sha256 "REPLACE_ME_DARWIN_X64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SectorOPS/Stash/releases/download/v0.1.0/stash-0.1.0-linux-arm64.tar.gz"
      sha256 "REPLACE_ME_LINUX_ARM64"
    end
    on_intel do
      url "https://github.com/SectorOPS/Stash/releases/download/v0.1.0/stash-0.1.0-linux-x64.tar.gz"
      sha256 "REPLACE_ME_LINUX_X64"
    end
  end

  def install
    bin.install "stash"
  end

  test do
    assert_match "stash #{version}", shell_output("#{bin}/stash --version")
  end
end
